# Generated by Django 5.2.3 on 2025-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_gallery_images_alter_gallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='mainapp.image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
